load("@io_bazel_rules_go//go:def.bzl", "go_library")

##
## Libraries
##
go_library(
    name = "random",
    srcs = ["random.go"],
    importpath = "github.com/BranLwyd/harpocrates/random/random",
)
